### ISSUE TITLE
Exception: ('Files folder path is not a directory.', '/Users/My-name/Desktop/Agency-Swarm/agency-swarm-lab/MetaMarkAgency/MetaMarkCEO/files')

### ISSUE THREAD

**Issue by Minhlele** [VRSEN/agency-swarm-lab#12]
I tried the local installation steps and after running` python agency.py ` for the facebook marketing agency, I encounter this error. Seems like it's trying to look for a files folder and that folder does not exsit. I tried updating agency-swarm to the newest version but that did not fix it!

**Comment by nasko94** [comment]
same thing with me

**Comment by Minhlele** [comment]
I actually resolved this by going to the individual agent file and manually commented out the files_folder and schemas_folder. i have attached an example of this below. 
![Screen Shot 2024-04-19 at 11 57 58](https://github.com/VRSEN/agency-swarm-lab/assets/98129114/dabfea64-119b-4fb4-8e61-8b176d42c8f1)
