### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by triffalin** [VRSEN/agency-swarm-lab#16]
in VSC terminal everything looks good:
"
seluser@187fbed20efe:/app/CodeSolutionAgency$ python agency.py
Files folder '/app/CodeSolutionAgency/PlannerAgent/files' is not a directory. Skipping...
Schemas folder path is not a directory. Skipping...  /app/CodeSolutionAgency/PlannerAgent/schemas
Files folder '/app/CodeSolutionAgency/Devid/files' is not a directory. Skipping...
Schemas folder path is not a directory. Skipping...  /app/CodeSolutionAgency/Devid/schemas
Files folder '/app/CodeSolutionAgency/BrowsingAgent/files' is not a directory. Skipping...
Schemas folder path is not a directory. Skipping...  /app/CodeSolutionAgency/BrowsingAgent/schemas
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.", but the page cannot be accessed in the browser.
![Screenshot 2024-04-21 211732](https://github.com/VRSEN/agency-swarm-lab/assets/110256756/79a9b52c-3e96-484a-b2ca-0cea6396bf8c)
![Screenshot 2024-04-21 211740](https://github.com/VRSEN/agency-swarm-lab/assets/110256756/8294e58e-4190-410a-9bca-a3b4e5f9f42c)

**Comment by newjxmaster** [comment]
try to m=paste the link in a chrome browser . if it still doesn't work you close the vscode then redo the process.. but only use chrome. I'm on Mac m2

**Comment by triffalin** [comment]
with small changes, it now works and runs automatically on localhost / http://127.0.0.1:7860 instead of 0.0.0.0:7860. this is the solution for agency.py from CodeSolutionAgency:

`from agency_swarm import Agency, set_openai_key
from BrowsingAgent import BrowsingAgent
from Devid import Devid
from PlannerAgent import PlannerAgent
import os

# load env from .env
from dotenv import load_dotenv
load_dotenv()

#set_openai_key(os.environ["OPENAI_API_KEY"])

planner = PlannerAgent()
devid = Devid()
browsingAgent = BrowsingAgent()

agency = Agency([planner, devid, browsingAgent, [planner, devid],
                 [planner, browsingAgent],
                 [devid, browsingAgent]],
                shared_instructions='./agency_manifesto.md')

if __name__ == '__main__':
    **agency.demo_gradio(height=400)**
    # agency.demo_gradio(server_name="0.0.0.0")
    # agency.run_demo()`
